--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/10/2018 1:40:51 PM
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE universidad;

--
-- Drop table `transporte`
--
DROP TABLE IF EXISTS transporte;

--
-- Drop table `clase`
--
DROP TABLE IF EXISTS clase;

--
-- Drop table `docente`
--
DROP TABLE IF EXISTS docente;

--
-- Drop table `estudiante`
--
DROP TABLE IF EXISTS estudiante;

--
-- Drop table `horarios`
--
DROP TABLE IF EXISTS horarios;

--
-- Set default database
--
USE universidad;

--
-- Create table `horarios`
--
CREATE TABLE horarios (
  codigoHorario int(6) NOT NULL AUTO_INCREMENT,
  codigoMateria int(6) NOT NULL,
  Paralelo int(5) NOT NULL,
  codigoDocente varchar(5) NOT NULL,
  PRIMARY KEY (codigoHorario)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `estudiante`
--
CREATE TABLE estudiante (
  codigoEstudiante int(5) NOT NULL AUTO_INCREMENT,
  codigoCuenta int(11) NOT NULL,
  Nombre varchar(25) NOT NULL,
  Apellido varchar(255) NOT NULL,
  CI int(9) NOT NULL,
  Fecha_Nacimiento date NOT NULL,
  Telefono varchar(7) NOT NULL,
  Direccion varchar(100) NOT NULL,
  PAA tinyint(1) NOT NULL,
  Semestre char(1) NOT NULL,
  Campus varchar(15) NOT NULL,
  Carrera varchar(100) NOT NULL,
  PRIMARY KEY (codigoEstudiante)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `docente`
--
CREATE TABLE docente (
  codigoDocente int(5) NOT NULL AUTO_INCREMENT,
  Nombre varchar(11) NOT NULL,
  Apellido varchar(15) NOT NULL,
  CI int(10) NOT NULL,
  Fecha_Nacimiento date NOT NULL,
  Telefono int(8) NOT NULL,
  Grado_Titulacion varchar(255) NOT NULL,
  Campus varchar(255) NOT NULL,
  Seguro_Medico int(11) NOT NULL,
  PRIMARY KEY (codigoDocente)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `clase`
--
CREATE TABLE clase (
  IDClase int(5) NOT NULL AUTO_INCREMENT,
  codigoDocente int(5) NOT NULL,
  codigoHorario int(5) NOT NULL,
  codigoEstudiante int(5) NOT NULL,
  PRIMARY KEY (IDClase)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE clase
ADD CONSTRAINT FK_clase_docente_codigoDocente FOREIGN KEY (codigoDocente)
REFERENCES docente (codigoDocente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE clase
ADD CONSTRAINT FK_clase_estudiante_codigoEstudiante FOREIGN KEY (codigoEstudiante)
REFERENCES estudiante (codigoEstudiante) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE clase
ADD CONSTRAINT FK_clase_horarios_codigoHorario FOREIGN KEY (codigoHorario)
REFERENCES horarios (codigoHorario) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `transporte`
--
CREATE TABLE transporte (
  codigoVehiculo int(5) NOT NULL AUTO_INCREMENT,
  codigoEstudiante int(5) NOT NULL,
  Placa varchar(6) NOT NULL,
  Marca varchar(100) NOT NULL,
  Color varchar(10) NOT NULL,
  Propietario varchar(30) NOT NULL,
  Soat tinyint(1) NOT NULL,
  PRIMARY KEY (codigoVehiculo)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table horarios
--
-- Table universidad.horarios does not contain any data (it is empty)

-- 
-- Dumping data for table estudiante
--
-- Table universidad.estudiante does not contain any data (it is empty)

-- 
-- Dumping data for table docente
--
-- Table universidad.docente does not contain any data (it is empty)

-- 
-- Dumping data for table transporte
--
-- Table universidad.transporte does not contain any data (it is empty)

-- 
-- Dumping data for table clase
--
-- Table universidad.clase does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;