--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/9/2018 11:21:21 p. m.
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE universidad;

--
-- Drop table `materia`
--
DROP TABLE IF EXISTS materia;

--
-- Drop table `carrera`
--
DROP TABLE IF EXISTS carrera;

--
-- Drop table `aula`
--
DROP TABLE IF EXISTS aula;

--
-- Drop table `cuenta`
--
DROP TABLE IF EXISTS cuenta;

--
-- Drop table `transporte`
--
DROP TABLE IF EXISTS transporte;

--
-- Drop table `estudiante`
--
DROP TABLE IF EXISTS estudiante;

--
-- Drop table `horarios`
--
DROP TABLE IF EXISTS horarios;

--
-- Drop table `notasyfaltas`
--
DROP TABLE IF EXISTS notasyfaltas;

--
-- Drop table `clase`
--
DROP TABLE IF EXISTS clase;

--
-- Drop table `docente`
--
DROP TABLE IF EXISTS docente;

--
-- Drop table `semestre`
--
DROP TABLE IF EXISTS semestre;

--
-- Set default database
--
USE universidad;

--
-- Create table `semestre`
--
CREATE TABLE semestre (
  IdSemestre int(11) NOT NULL AUTO_INCREMENT,
  Modulo int(11) NOT NULL,
  Año year(4) NOT NULL,
  PRIMARY KEY (IdSemestre)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `docente`
--
CREATE TABLE docente (
  CodigoDocente int(11) NOT NULL AUTO_INCREMENT,
  Nombres varchar(255) NOT NULL,
  Apellidos varchar(255) NOT NULL,
  Titulacion varchar(255) NOT NULL,
  SeguroMedico varchar(255) NOT NULL,
  FechaDeNacimiento date NOT NULL,
  Celular int(11) NOT NULL,
  PRIMARY KEY (CodigoDocente)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `clase`
--
CREATE TABLE clase (
  IdClase int(11) NOT NULL AUTO_INCREMENT,
  CodigoDocente int(11) NOT NULL,
  IdSemestre int(11) NOT NULL,
  PRIMARY KEY (IdClase)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE clase
ADD CONSTRAINT FK_clase_docente_CodigoDocente FOREIGN KEY (CodigoDocente)
REFERENCES docente (CodigoDocente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE clase
ADD CONSTRAINT FK_clase_semestre_IdSemestre FOREIGN KEY (IdSemestre)
REFERENCES semestre (IdSemestre) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `notasyfaltas`
--
CREATE TABLE notasyfaltas (
  IdClase int(11) NOT NULL AUTO_INCREMENT,
  Faltas int(11) NOT NULL,
  Parcial int(11) NOT NULL,
  NotaFinal int(11) NOT NULL,
  PRIMARY KEY (IdClase)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE notasyfaltas
ADD CONSTRAINT PK_notasyfaltas_clase_IdClase FOREIGN KEY (IdClase)
REFERENCES clase (IdClase) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `horarios`
--
CREATE TABLE horarios (
  CodigoHorario int(11) NOT NULL AUTO_INCREMENT,
  Paralelo varchar(5) NOT NULL,
  IdClase int(11) NOT NULL,
  Modalidad varchar(255) NOT NULL,
  FechaInicio date NOT NULL,
  FechaFinal date NOT NULL,
  PRIMARY KEY (CodigoHorario)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE horarios
ADD CONSTRAINT FK_horarios_clase_IdClase FOREIGN KEY (IdClase)
REFERENCES clase (IdClase) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `estudiante`
--
CREATE TABLE estudiante (
  CodigoEstudiante int(11) NOT NULL AUTO_INCREMENT,
  CodigoCuenta int(11) NOT NULL,
  Nombres varchar(255) NOT NULL,
  Apellidos varchar(255) NOT NULL,
  FechaNacimiento date NOT NULL,
  Telefono int(8) NOT NULL,
  Direccion varchar(255) NOT NULL,
  PAA tinyint(1) NOT NULL,
  CI varchar(255) NOT NULL,
  IdClase int(11) NOT NULL,
  PRIMARY KEY (CodigoEstudiante)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `UK_estudiante_CodigoCuenta` on table `estudiante`
--
ALTER TABLE estudiante
ADD UNIQUE INDEX UK_estudiante_CodigoCuenta (CodigoCuenta);

--
-- Create foreign key
--
ALTER TABLE estudiante
ADD CONSTRAINT FK_estudiante_clase_IdClase FOREIGN KEY (IdClase)
REFERENCES clase (IdClase) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `transporte`
--
CREATE TABLE transporte (
  CodigoVehiculo int(11) NOT NULL AUTO_INCREMENT,
  CodigoEstudiante int(11) NOT NULL,
  Placa varchar(255) NOT NULL,
  Marca varchar(255) NOT NULL,
  Color varchar(255) NOT NULL,
  Soat varchar(255) NOT NULL,
  PRIMARY KEY (CodigoVehiculo)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE transporte
ADD CONSTRAINT FK_transporte_estudiante_CodigoEstudiante FOREIGN KEY (CodigoEstudiante)
REFERENCES estudiante (CodigoEstudiante) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `cuenta`
--
CREATE TABLE cuenta (
  CodigoCuenta int(11) NOT NULL AUTO_INCREMENT,
  SaldoPagar decimal(10, 2) NOT NULL,
  ImportePagado decimal(10, 2) NOT NULL,
  DescuentoBeca decimal(10, 2) NOT NULL,
  PlanDePagos varchar(255) NOT NULL,
  PRIMARY KEY (CodigoCuenta)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE cuenta
ADD CONSTRAINT PK_cuenta_estudiante_CodigoCuenta FOREIGN KEY (CodigoCuenta)
REFERENCES estudiante (CodigoCuenta) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `aula`
--
CREATE TABLE aula (
  IdAula int(11) NOT NULL AUTO_INCREMENT,
  IdClase int(11) NOT NULL,
  PRIMARY KEY (IdAula)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE aula
ADD CONSTRAINT FK_aula_clase_IdClase FOREIGN KEY (IdClase)
REFERENCES clase (IdClase) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `carrera`
--
CREATE TABLE carrera (
  IdCarrera int(11) NOT NULL AUTO_INCREMENT,
  JefeDeCarrera varchar(255) NOT NULL,
  Nombre varchar(255) NOT NULL,
  PRIMARY KEY (IdCarrera)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `materia`
--
CREATE TABLE materia (
  CodigoMateria int(11) NOT NULL AUTO_INCREMENT,
  Creditos int(11) NOT NULL,
  Estado varchar(255) NOT NULL,
  IdCarrera int(11) NOT NULL,
  IdClase int(11) NOT NULL,
  PRIMARY KEY (CodigoMateria)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE materia
ADD CONSTRAINT FK_materia_carrera_IdCarrera FOREIGN KEY (IdCarrera)
REFERENCES carrera (IdCarrera) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE materia
ADD CONSTRAINT FK_materia_clase_IdClase FOREIGN KEY (IdClase)
REFERENCES clase (IdClase) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table semestre
--
-- Table universidad.semestre does not contain any data (it is empty)

-- 
-- Dumping data for table docente
--
-- Table universidad.docente does not contain any data (it is empty)

-- 
-- Dumping data for table clase
--
-- Table universidad.clase does not contain any data (it is empty)

-- 
-- Dumping data for table carrera
--
-- Table universidad.carrera does not contain any data (it is empty)

-- 
-- Dumping data for table estudiante
--
-- Table universidad.estudiante does not contain any data (it is empty)

-- 
-- Dumping data for table transporte
--
-- Table universidad.transporte does not contain any data (it is empty)

-- 
-- Dumping data for table notasyfaltas
--
-- Table universidad.notasyfaltas does not contain any data (it is empty)

-- 
-- Dumping data for table materia
--
-- Table universidad.materia does not contain any data (it is empty)

-- 
-- Dumping data for table horarios
--
-- Table universidad.horarios does not contain any data (it is empty)

-- 
-- Dumping data for table cuenta
--
-- Table universidad.cuenta does not contain any data (it is empty)

-- 
-- Dumping data for table aula
--
-- Table universidad.aula does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;